# 1. Numpy 생성
넘파이 실행 내용

In [1]:
import numpy as np

In [2]:
t_arr = np.array([1, 4, 5, 8], float)
t_arr

array([1., 4., 5., 8.])

In [3]:
type(t_arr)

numpy.ndarray

In [4]:
type(t_arr[0])

numpy.float64

In [5]:
print(t_arr.dtype)

float64


In [6]:
print(t_arr.shape)

(4,)


In [7]:
mix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(mix).shape

(3, 4)

In [8]:
t_3 = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
      [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
      [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
      [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
      ]
np.array(t_3).shape

(4, 3, 4)

In [10]:
np.array(t_3).ndim

3

In [11]:
np.array(t_3).size

48

In [12]:
np.array([[1, 2, 3], [4, 5, 6]], dtype = int)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7])
x.reshape(2, -1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
x.reshape(2, 2, -1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
l = [[1, 2, 3, 4], [5, 6, 7, 8]]
l[0][0]

1

In [17]:
x = np.array(l)
x[0][0]

1

In [18]:
x[0,0]

1

In [19]:
x = np.array([ [ [1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1, 2, 3, 4, 5]]
              , [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1, 2, 3, 4, 5] ] ])
x.shape

(2, 3, 5)

In [20]:
x[1, 2, 3]

4

In [21]:
x = np.array([ [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]])
x[:2, ::2]

array([[1, 5],
       [1, 5]])

In [22]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1, 100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.arange(1, 100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [28]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.eye(N=3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [30]:
np.eye(N=3, M=5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [31]:
mix = np.arange(9).reshape(3,3)
mix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
np.diag(mix, k=1)

array([1, 5])