# 2. Numpy 연산
연산을 통한 결과

In [1]:
import numpy as np

t_a = np.arange(1, 11)
t_a.sum()

55

In [2]:
t_a = np.arange(1, 13).reshape(3, 4)
t_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

고차원에서의 출발로 고차원의 축을 이야기한다.

In [3]:
t_a.sum(axis = 0)

array([15, 18, 21, 24])

In [4]:
t_a.sum(axis = 1)

array([10, 26, 42])

In [6]:
t_a_2 = np.array([t_a, t_a, t_a])
t_a_2.shape

(3, 3, 4)

In [7]:
t_a_2.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [8]:
t_a_2.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [9]:
t_a_2.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [11]:
v_a = np.array([1, 2, 3])
v_a_1 = np.array([4, 5, 6])
np.vstack((v_a, v_a_1))

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
h_1 = v_a.reshape(-1, 1)
h_2 = v_a_1.reshape(-1, 1)
np.hstack((h_1, h_2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
x % x

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
x * x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [21]:
x ** x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [22]:
x == x

array([[ True,  True,  True],
       [ True,  True,  True]])

In [24]:
heights = np.array([1.83, 1.76, 1.69, 1.86, 1.77, 1.73])
weights = [86, 74, 59, 95, 80, 68]
BMI = weights/heights**2
BMI

array([25.68007405, 23.88946281, 20.65754   , 27.45982194, 25.53544639,
       22.72043837])

In [25]:
x = np.arange(1, 7).reshape(2, 3)
y = np.arange(1, 7).reshape(3, 2)
np.dot(x, y)

array([[22, 28],
       [49, 64]])

In [26]:
x.dot(y)

array([[22, 28],
       [49, 64]])

In [27]:
x = np.arange(1, 13).reshape(4, 3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
v = np.array([10, 20, 30])
v

array([10, 20, 30])

In [30]:
x + v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [32]:
v2 = np.array([1, 2, 3, 4]).reshape(-1, 1)
v2

array([[1],
       [2],
       [3],
       [4]])

In [33]:
x + v2

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [34]:
v + v2

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [35]:
x = np.arange(3, 10)
x

array([3, 4, 5, 6, 7, 8, 9])

In [36]:
x > 5

array([False, False, False,  True,  True,  True,  True])

In [37]:
(x > 5).all()

False

In [38]:
(x > 5).any()

True

In [39]:
(x < 1).all()

False

In [40]:
(x < 1).any()

False

In [41]:
(x > 2).all()

True

In [42]:
(x > 2).any()

True

In [43]:
scorelist = np.array(np.random.randint(0, 100, 100))
scorelist

array([42, 55, 98, 87, 49, 82, 28, 19, 94, 24, 18, 46,  1, 65, 66,  0, 40,
       21, 27, 71,  7, 26, 14, 97, 77,  0, 76, 45, 15, 35, 59,  4, 82, 28,
       95,  9, 97, 95, 96, 23, 20, 92,  2, 74, 60, 68, 19, 38, 62, 62, 36,
       12, 99, 68, 53,  7, 80, 19, 91, 92,  1, 14, 44, 92, 84, 67, 18,  5,
       76, 11, 43,  2, 38, 54, 58, 43, 21, 58,  2, 57, 75, 81, 90,  1, 21,
        5, 31, 96, 82, 53, 76,  9, 25, 60, 99, 97, 88, 29,  4, 15])

In [44]:
scorelist.mean()

47.92

In [46]:
if scorelist.mean() > 50:
    print('전원통과')
else :
    print('전원통과 아님')

전원통과 아님


In [50]:
x = np.array([1, 2, 3, 4, 5, 1])
np.where(x == 1, 10, 20)

array([10, 20, 20, 20, 20, 10])

x == 1인지 비교 후 참이면 10, 거짓이면 20

In [51]:
d = np.array([1, 5, 3, 7, 2, 8, 4])
np.argsort(d)

array([0, 4, 2, 6, 1, 3, 5])

In [52]:
d >= 5

array([False,  True, False,  True, False,  True, False])

In [53]:
d[d >= 5]

array([5, 7, 8])

In [54]:
x = np.arange(1, 11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
l = np.array([0, 5, 9, 0, 0, 0])
x[l]

array([ 1,  6, 10,  1,  1,  1])

In [56]:
x = x.reshape(2, -1)
i_1 = np.array([0, 1])
i_0 = np.array([1, 0])
print(x)
x[i_0, i_1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([6, 2])

In [57]:
x_l = np.array([x, x, x])
x_l

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [58]:
x_l[:, :, :4]

array([[[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[1, 2, 3, 4],
        [6, 7, 8, 9]]])